In [ ]:
#BANKING DATA ANALYSIS
#The assignment uses banking industry data with 10 rows × 5 columns:

#Customer_ID: Unique identifier for each customer
#Account_Balance: Customer's account balance in dollars
#Credit_Score: Customer's credit score (300-900 range)
#Transaction_Count: Number of transactions in the last month
#Years_Active: Number of years the customer has been with

In [5]:
import numpy as np
print("=" * 60)
print("NUMPY ASSIGNMENT: BANKING DATA ANALYSIS")
print("=" * 60)
# Create banking_data: 10 rows × 5 columns
# Columns: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [1001, 125000, 745, 42, 15],
    [1002, 89000, 632, 45, 8],
    [1003, 45000, 878, 38, 22],
    [1004, 25000, 712, 47, 5],
    [1005, 75000, 895, 40, 18],
    [1006, 18000, 628, 43, 12],
    [1007, 95000, 756, 39, 20],
    [1008, 320000, 718, 46, 7],
    [1009, 65000, 867, 41, 16],
    [1010, 140000, 734, 44, 10]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")


NUMPY ASSIGNMENT: BANKING DATA ANALYSIS

ORIGINAL BANKING DATA:
[[  1001 125000    745     42     15]
 [  1002  89000    632     45      8]
 [  1003  45000    878     38     22]
 [  1004  25000    712     47      5]
 [  1005  75000    895     40     18]
 [  1006  18000    628     43     12]
 [  1007  95000    756     39     20]
 [  1008 320000    718     46      7]
 [  1009  65000    867     41     16]
 [  1010 140000    734     44     10]]

Data shape: (10, 5)
Data type: int64


In [ ]:
#Q1:ARRAY CREATION AND MANIPULATION


#Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Q1.2: Create an array of 8 zeros using np.zeros()
zeros_array = np.zeros(8)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Q1.3: Create an array of 6 ones using np.ones()
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [ ]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
range_array = np.arange(16)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
linspace_array = np.linspace(0,100,8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [ ]:
#Question 2: Array Attributes and Information

#Q2.1: What is the shape of the banking_data array?
x = banking_data.shape
print(x)

(10, 5)


In [ ]:
#Q2.2: What is the data type of the banking_data array?
x = banking_data.dtype
print(x)

float64


In [ ]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
x = banking_data.size
print(x)

50


In [ ]:
#Q2.4: What is the number of dimensions of the banking_data array?
x = banking_data.ndim
print(x)

2


In [ ]:
#Q2.5: What is the memory size of the banking_data array in bytes?
x = banking_data.nbytes
print(x)

400


In [ ]:
#Question 3: Indexing and Slicing


#Q3.1: Extract the first row of banking_data
first_row = banking_data[0]
print(first_row)

[  1001 125000    745     42     15]


In [ ]:
#Q3.2: Extract the last row of banking_data
last_row = banking_data[-1]
print(last_row)

[  1010 140000    734     44     10]


In [ ]:
#Q3.3: Extract the Account_Balance column (column index 1)
account_balance = banking_data[:,1]
print(account_balance)


[125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]


In [ ]:
#Q3.4: Extract the first 4 rows and first 3 columns
s = banking_data[:4, :3]
print(s)


[[  1001 125000    745]
 [  1002  89000    632]
 [  1003  45000    878]
 [  1004  25000    712]]


In [ ]:
#Q3.5: Extract rows 3 to 7 (inclusive)
s = banking_data[3:8]
print(s)

[[  1004  25000    712     47      5]
 [  1005  75000    895     40     18]
 [  1006  18000    628     43     12]
 [  1007  95000    756     39     20]
 [  1008 320000    718     46      7]]


In [ ]:
#Question 4: Mathematical Operations

#Q4.1: Calculate the sum of all account balances
s = banking_data[:, 1]
print(np.sum(s))


997000


In [ ]:
#Q4.2: Calculate the mean account balance
s = banking_data[:,1]
print(np.mean(s))

99700.0


In [ ]:
#Q4.3: Calculate the standard deviation of account balances
s = banking_data[:, 1]
print(np.std(s))

82458.53503428254


In [ ]:
#Q4.4: Calculate the variance of account balances
s = banking_data[:,1]
print(np.var(s))

6799410000.0


In [ ]:
#Q4.5: Calculate the median account balance
s = banking_data[:,1]
print(np.median(s))

82000.0


In [ ]:
#Question 5: Statistical Functions


#Q5.1: Find the minimum and maximum account balances
s = banking_data[:,1]
print(np.min(s))
print(np.max(s))

18000
320000


In [ ]:
#Q5.2: Find the minimum and maximum credit scores
s = banking_data[:,2]
print(np.min(s))
print(np.max(s))

628
895


In [ ]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
s = banking_data[:,1]
print(np.percentile(s,[25, 50, 75]))

[ 50000.  82000. 117500.]


In [ ]:
#Q5.4: Calculate the correlation between account balance and credit score
s = banking_data[:,1]
r = banking_data[:,2]
print(np.corrcoef(s,r))

[[ 1.         -0.11262639]
 [-0.11262639  1.        ]]


In [ ]:
#Q5.5: Calculate the covariance between account balance and credit score
s = banking_data[:,1]
r = banking_data[:,2]
print(np.cov(s,r))

[[ 7.55490000e+09 -9.35944444e+05]
 [-9.35944444e+05  9.14094444e+03]]


In [ ]:
#Question 6: Array Reshaping and Manipulation


#Q6.1: Reshape the banking_data to 5 rows × 10 columns
s = banking_data.reshape(5,10)
print(s)

[[  1001 125000    745     42     15   1002  89000    632     45      8]
 [  1003  45000    878     38     22   1004  25000    712     47      5]
 [  1005  75000    895     40     18   1006  18000    628     43     12]
 [  1007  95000    756     39     20   1008 320000    718     46      7]
 [  1009  65000    867     41     16   1010 140000    734     44     10]]


In [ ]:
#Q6.2: Flatten the banking_data to a 1D array
s = banking_data.flatten()
print(s)

[  1001 125000    745     42     15   1002  89000    632     45      8
   1003  45000    878     38     22   1004  25000    712     47      5
   1005  75000    895     40     18   1006  18000    628     43     12
   1007  95000    756     39     20   1008 320000    718     46      7
   1009  65000    867     41     16   1010 140000    734     44     10]


In [ ]:
#Q6.3: Transpose the banking_data
s = banking_data.T
print(s)

[[  1001   1002   1003   1004   1005   1006   1007   1008   1009   1010]
 [125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]
 [   745    632    878    712    895    628    756    718    867    734]
 [    42     45     38     47     40     43     39     46     41     44]
 [    15      8     22      5     18     12     20      7     16     10]]


In [ ]:
#Q6.4:Split the banking_data into 2 equal parts vertically
s,r = np.vsplit(banking_data, 2)
print(s,r)



[[  1001 125000    745     42     15]
 [  1002  89000    632     45      8]
 [  1003  45000    878     38     22]
 [  1004  25000    712     47      5]
 [  1005  75000    895     40     18]] [[  1006  18000    628     43     12]
 [  1007  95000    756     39     20]
 [  1008 320000    718     46      7]
 [  1009  65000    867     41     16]
 [  1010 140000    734     44     10]]


In [ ]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
s,r = np.hsplit(banking_data,[3])
print(s,r)


[[  1001 125000    745]
 [  1002  89000    632]
 [  1003  45000    878]
 [  1004  25000    712]
 [  1005  75000    895]
 [  1006  18000    628]
 [  1007  95000    756]
 [  1008 320000    718]
 [  1009  65000    867]
 [  1010 140000    734]] [[42 15]
 [45  8]
 [38 22]
 [47  5]
 [40 18]
 [43 12]
 [39 20]
 [46  7]
 [41 16]
 [44 10]]


In [ ]:
#Question 7: Logical Operations and Filtering


#Q7.1: Find customers with account balance greater than $100,000
s = banking_data[:,1]>100000
r = tuple(s)
print(r.count(True))

3


In [ ]:
#Q7.2: Find customers with credit score greater than 800
s = banking_data[:,2]>800
r = tuple(s)
print(r.count(True))

3


In [ ]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
s = (banking_data[:,3]>50) &(banking_data[:,2]<750)
r = tuple(s)
print(r.count(True))

0


In [ ]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
s = banking_data[:,1]
r = (s > 10000) & (s < 100000)
print(tuple(r).count(True))


7


In [ ]:
#Q7.5: Find the index of the customer with the highest credit score
s = banking_data[:,2]
print(np.argmax(s))

4


In [ ]:
#Question 8: Sorting and Searching


#Q8.1: Sort the banking_data by account balance (ascending)
s = banking_data[:,1]
print(np.argsort(s))

[5 3 2 8 4 1 6 0 9 7]


In [ ]:
#Q8.2: Sort the banking_data by credit score (descending)
s = banking_data[:,2]
print(np.argsort(s))

[5 1 3 7 9 0 6 8 2 4]


In [ ]:
#Q8.3: Find the indices that would sort the array by years active
s = banking_data[:,-1]
print(np.argsort(s))

[3 7 1 9 5 0 8 4 6 2]


In [ ]:
#Q8.4: Find the customer with the second highest account balance
s = banking_data[:,1]
y = np.sort(s)
print(y[-2])

140000


In [ ]:
#Q8.5: Find the customer with the lowest transaction count
s = banking_data[:,-2]
r = np.argmin(s)
print(r)

2


In [ ]:
#Question 9: Mathematical Functions


#Q9.1: Calculate the absolute values of all elements
s = banking_data
print(np.abs(s))

[[  1001  18000    745     42     15]
 [  1002  25000    632     45      8]
 [  1003  45000    878     38     22]
 [  1004  65000    712     47      5]
 [  1005  75000    895     40     18]
 [  1006  89000    628     43     12]
 [  1007  95000    756     39     20]
 [  1008 125000    718     46      7]
 [  1009 140000    867     41     16]
 [  1010 320000    734     44     10]]


In [ ]:
#Q9.2: Calculate the square root of all account balances
s = banking_data[:,1]
print(np.sqrt(s))


[134.16407865 158.11388301 212.13203436 254.95097568 273.86127875
 298.3286778  308.22070015 353.55339059 374.16573868 565.68542495]


In [ ]:
#Q9.3: Calculate the square of all credit scores

s = banking_data[:,2]
print(np.square(s))


[555025 399424 770884 506944 801025 394384 571536 515524 751689 538756]


In [ ]:
#Q9.4: Calculate the exponential of all transaction counts
s = banking_data[:,3]
print(np.exp(s))


[1.73927494e+18 3.49342711e+19 3.18559318e+16 2.58131289e+20
 2.35385267e+17 4.72783947e+18 8.65934004e+16 9.49611942e+19
 6.39843494e+17 1.28516001e+19]


In [ ]:
#Q9.5: Calculate the natural logarithm of all account balances
s = banking_data[:,1]
print(np.log(s))

[ 9.79812704 10.1266311  10.71441777 11.08214255 11.22524339 11.39639165
 11.46163217 11.73606902 11.8493977  12.67607627]


In [ ]:
#Question 10: Advanced Operations



#Q10.1: Calculate the cumulative sum of account balances
s = banking_data[:,1]
print(np.cumsum(s))

[ 18000  43000  88000 153000 228000 317000 412000 537000 677000 997000]


In [ ]:
#Q10.2: Calculate the cumulative product of transaction counts
s = banking_data[:,3]
print(np.cumprod(s))

[               42              1890             71820           3375540
         135021600        5805928800      226431223200    10415836267200
   427049286955200 18790168626028800]


In [ ]:
#Q10.3: Calculate the difference between consecutive account balances
s = banking_data[:,1]
print(np.diff(s))

[  7000  20000  20000  10000  14000   6000  30000  15000 180000]


In [ ]:
#Q10.4: Calculate the gradient of account balances
s = banking_data[:,1]
print(np.gradient(s))

[  7000.  13500.  20000.  15000.  12000.  10000.  18000.  22500.  97500.
 180000.]


In [ ]:
#Q10.5: Calculate the histogram of account balances with 5 bins
s,r = np.histogram(banking_data[:,1],bins=5)
print(s,r)

[5 3 1 0 1] [ 18000.  78400. 138800. 199200. 259600. 320000.]


In [ ]:
#Question 11: Random Numbers and Simulation


#Q11.1: Generate 6 random integers between 1 and 1000
s = np.random.randint(1,1001,6)
print(s)

[618 684 723 327 726 906]


In [ ]:
#Q11.2: Generate 6 random floats between 0 and 1
s = np.random.random(6)
print(s)

[0.22005927 0.9020154  0.54545147 0.23875036 0.2176603  0.52006391]


In [ ]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
s = np.random.normal(700,100,6)
print(s)


[648.95686887 579.85859722 753.08550033 658.11733638 816.38776051
 689.33319029]


In [ ]:
#Q11.4: Shuffle the banking_data rows randomly
s = banking_data.copy()
np.random.shuffle(s)
print(s)


[[  1002  25000    632     45      8]
 [  1006  89000    628     43     12]
 [  1004  65000    712     47      5]
 [  1007  95000    756     39     20]
 [  1001  18000    745     42     15]
 [  1003  45000    878     38     22]
 [  1008 125000    718     46      7]
 [  1010 320000    734     44     10]
 [  1005  75000    895     40     18]
 [  1009 140000    867     41     16]]


In [ ]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
s = np.random.random(4)
print(s)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [ ]:
#Question 12: Linear Algebra



#Q12.1: Calculate the dot product of account balance and credit score columns
s = banking_data[:, 1]
r = banking_data[:, 2]
print(np.dot(s, r))


755847000


In [ ]:
#Q12.2: Calculate the cross product of first two rows
s = banking_data[0,:3]
r = banking_data[1,:3]
print(np.cross(s,r))

[-7249000   113858  6989000]


In [ ]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
s = banking_data[:,1]
print(np.linalg.norm(s))


409139.34056748933


In [ ]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
s = np.array([[1, 4, 3], [2, 5, 6], [5, 8, 9]])
r = np.linalg.det(s)
print(r)


17.999999999999996


In [ ]:
#Q12.5: Calculate the inverse of the 3x3 matrix
x = np.linalg.inv(s)
print(x)

[[-1.66666667e-01 -6.66666667e-01  5.00000000e-01]
 [ 6.66666667e-01 -3.33333333e-01 -1.15648232e-17]
 [-5.00000000e-01  6.66666667e-01 -1.66666667e-01]]


In [ ]:
#Question 13: String Operations


#Q13.1: Convert all customer IDs to strings
s = banking_data[:,0].astype(str)
print(s)

['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010']


In [ ]:
#Q13.2: Check if any customer ID contains '100'
r = banking_data[:, 0].astype(str)
k = np.char.find(r, '100')
print(r,k)

['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010'] [ 0  0  0  0  0  0  0  0  0 -1]


In [ ]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
j = np.char.upper(r)
print(j)


['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010']


In [ ]:
#Q13.4: Count the length of each customer ID string
j = np.char.str_len(r)
print(j)

[4 4 4 4 4 4 4 4 4 4]


In [ ]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
k = np.char.replace(r,'100','CUST')
print(k)

['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '1010']


In [ ]:
#Question 14: Date and Time Operations


#Q14.1: Convert years active to months
s = banking_data[:,-1] * 12
print(s)

[180  96 264  60 216 144 240  84 192 120]


In [ ]:
#Q14.2: Calculate the average years active
s = banking_data[:,-1]
print(np.mean(s))


13.3


In [ ]:
#Q14.3: Find customers who have been active for more than 5 years
s = banking_data[:,-1]>5
r = tuple(s)
print(r.count(True))

9


In [ ]:
#Q14.4: Calculate the total time all customers have been active (in years)
s = banking_data[:,-1]
print(np.sum(s))

133


In [ ]:
#Q14.5: Find the customer with the shortest time active
s = banking_data[:, -1]
r = np.argmin(s)
print (s,r)




[15  8 22  5 18 12 20  7 16 10] 3


In [ ]:
#Question 15: Advanced Array Operations


#Q15.1: Apply a function to calculate 5% interest on all account balances
s= banking_data[:, 1]
y=0.05*s
print(y)


[ 6250.  4450.  2250.  1250.  3750.   900.  4750. 16000.  3250.  7000.]


In [ ]:
#Q15.2: Use np.where to categorize customers by balance ranges
s = banking_data[:, 1]
x = np.where(s > 100000, 'High', np.where(s < 1000, 'Low', 'Medium'))
print(x)

['High' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'High'
 'Medium' 'High']


In [ ]:
#Q15.3: Use np.select to categorize customers by credit score ranges
s = banking_data[:, 2]
x = np.select([s > 800, s < 300], ['High', 'Low'], default='Medium')
print(x)


['Medium' 'Medium' 'High' 'Medium' 'High' 'Medium' 'Medium' 'Medium'
 'High' 'Medium']


In [ ]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance



In [8]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row
s = np.apply_along_axis( np.sum,1,banking_data)
print(s)

[126803  90687  46941  26768  76958  19689  96822 321779  66933 141798]


In [ ]:
#Question 16: Array Concatenation and Stacking


#Q16.1: Concatenate two arrays horizontally using np.hstack()
s=banking_data[:,0]
r=banking_data[:,1]
x=np.hstack((s,r))
print(x)

[  1001   1002   1003   1004   1005   1006   1007   1008   1009   1010
 125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]


In [ ]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
s=banking_data[:,0]
r=banking_data[:,1]
x=np.vstack((s,r))
print(x)

[[  1001   1002   1003   1004   1005   1006   1007   1008   1009   1010]
 [125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]]


In [ ]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
s=banking_data[:,0]
r=banking_data[:,1]
x=np.concatenate((s,r))
print(x)

[  1001   1002   1003   1004   1005   1006   1007   1008   1009   1010
 125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]


In [ ]:
#Q16.4: Stack arrays depth-wise using np.dstack()
s=banking_data[:,0]
r=banking_data[:,1]
x=np.dstack((s,r))
print(x)

[[[  1001 125000]
  [  1002  89000]
  [  1003  45000]
  [  1004  25000]
  [  1005  75000]
  [  1006  18000]
  [  1007  95000]
  [  1008 320000]
  [  1009  65000]
  [  1010 140000]]]


In [ ]:
#Q16.5: Create a column stack using np.column_stack()
s=banking_data[:,0]
r=banking_data[:,1]
x=np.column_stack((s,r))
print(x)

[[  1001 125000]
 [  1002  89000]
 [  1003  45000]
 [  1004  25000]
 [  1005  75000]
 [  1006  18000]
 [  1007  95000]
 [  1008 320000]
 [  1009  65000]
 [  1010 140000]]


In [ ]:
#Question 17: Array Splitting Operations


#Q17.1: Split an array into 3 equal parts using np.split()
s=banking_data[:,1]
r=np.array_split(s,3)
print(r)

[array([125000,  89000,  45000,  25000]), array([75000, 18000, 95000]), array([320000,  65000, 140000])]


In [ ]:
#Q17.2: Split an array at specific indices using np.split()
s=banking_data[:,1]
r=np.split(s,[3,7])
print(r)

[array([125000,  89000,  45000]), array([25000, 75000, 18000, 95000]), array([320000,  65000, 140000])]


In [ ]:
#Q17.3: Split an array horizontally using np.hsplit()
s=banking_data[:,1]
r=np.hsplit(s,2)
print(r)

[array([125000,  89000,  45000,  25000,  75000]), array([ 18000,  95000, 320000,  65000, 140000])]


In [ ]:
#Q17.4: Split an array vertically using np.vsplit()
s=banking_data[:,1]
r=banking_data[:,2]
k=np.vstack((s,r))
print(k)

[[125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]
 [   745    632    878    712    895    628    756    718    867    734]]


In [ ]:
#Q17.5: Split an array into equal chunks using np.array_split()
s=banking_data[:,1]
r= np.array_split(s, 4)
print(r)

[array([125000,  89000,  45000]), array([25000, 75000, 18000]), array([ 95000, 320000]), array([ 65000, 140000])]


In [ ]:
#Question 18: Array Repetition and Tiling



#Q18.1: Repeat each element of an array 3 times using np.repeat()
s=banking_data[:,1]
r=np.repeat(s,3)
print(r)

[125000 125000 125000  89000  89000  89000  45000  45000  45000  25000
  25000  25000  75000  75000  75000  18000  18000  18000  95000  95000
  95000 320000 320000 320000  65000  65000  65000 140000 140000 140000]


In [ ]:
#Q18.2: Repeat an entire array 2 times using np.tile()
s=banking_data[:,1]
r=np.tile(s,2)
print(r)

[125000  89000  45000  25000  75000  18000  95000 320000  65000 140000
 125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]


In [ ]:
#Q18.3: Repeat a 2D array using np.tile()
s=banking_data[:,1]
r=s.reshape(1,-1)
k=np.tile(r,(2,2))
print(k)

[[125000  89000  45000  25000  75000  18000  95000 320000  65000 140000
  125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]
 [125000  89000  45000  25000  75000  18000  95000 320000  65000 140000
  125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]]


In [ ]:
#Q18.4: Create a pattern using np.tile()
s=banking_data[:,1]
r=np.tile(s,1)
print(r)

[125000  89000  45000  25000  75000  18000  95000 320000  65000 140000]


In [ ]:
#Q18.5: Repeat elements with different counts using np.repeat()
s=banking_data[:,1]
r=[1,2,3,1,3,3,2,1,1,1]
k=np.repeat(s,r)
print(k)

[125000  89000  89000  45000  45000  45000  25000  75000  75000  75000
  18000  18000  18000  95000  95000 320000  65000 140000]


In [13]:
#Question 19: Array Comparison and Logical Operations
#Q19.1: Compare two arrays for equality using np.array_equal()
array1 = np.array([4,5,6])
array2 = np.array([7,8,9])
s = np.array_equal(array1,array2)
print(s)


False


In [14]:
#Q19.2: Check if arrays are close using np.allclose()
s = np.allclose(array1,array2)
print(s)

False


In [25]:
#Q19.3: Apply logical AND operation between arrays
s = np.logical_and(array1 > 4, array2 > 7)
print(s)

[False  True  True]


In [26]:
#Q19.4: Apply logical OR operation between arrays
s = np.logical_or(array1 > 4, array2 > 7)
print(s)

[False  True  True]


In [27]:
#Q19.5: Apply logical NOT operation to an array
s = np.logical_not(array1 == 4)
print(s)

[False  True  True]


In [28]:
#Question 20: Array Set Operations


#Q20.1: Find unique elements in an array using np.unique()
s = np.array([1,1,4,3,3,5,6,6,8])
print(np.unique(s))


[1 3 4 5 6 8]


In [33]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
array1 = np.array([3,4,5])
array2 = np.array([4,7,8])
s = np.intersect1d(array1,array2)
print(s)

[4]


In [35]:
#Q20.3: Find the union of two arrays using np.union1d()
s = np.union1d(array1,array2)
print(s)

[3 4 5 7 8]


In [36]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
s = np.setdiff1d(array1,array2)
print(s)

[3 5]


In [38]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
s = np.setxor1d(array1,array2)
print(s)

[3 5 7 8]
