In [2]:
import numpy as np

retail_data = np.array([[ 1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [26]:
#1. What is the **total revenue** generated across all stores?
y=retail_data[:,1]
print(sum(y))

335000


In [25]:
#2. Which store recorded the **highest sales**?
y=retail_data[:,1].argmax()+1
print(y)

9


In [28]:
#3. Which store recorded the **lowest sales**?
y=retail_data[:,1].argmin()+1
print(y)

1


In [50]:
#4. What is the **average daily sales** per store?
y=retail_data[:,1].mean()
print(y)

33500.0


In [61]:
#5. How many stores achieved sales **above ₹35,000**?
y = retail_data[:,1]
x=y>35000
z=tuple(x)
z.count(True)

3

**Customer Insights**

In [63]:
#6. Which store had the **highest customer footfall**?
y=retail_data[:,2].argmax()+1
print(y)

9


In [64]:
#7. What is the **average number of customers** per store?
y=retail_data[:,2].mean()
print(y)

425.0


In [65]:
#8. How many stores have **more than 450 customers**?
y = retail_data[:,2]
x=y>450
z=tuple(x)
z.count(True)

3

In [67]:
#9. Which store has the **lowest customer count**?
y=retail_data[:,2].argmin()+1
print(y)

0


In [104]:
#10. Is there any store where **high sales do not correspond to high customers**?
y=retail_data[:,2]
x=retail_data[:,1]
x=np.corrcoef(x,y)
len(x)

2

**Inventory & Returns Analysis**

In [77]:
#11. What is the **total inventory** across all stores?
y=retail_data[:,3].sum()
print(y)

14300


In [78]:
#12. Which store has the **highest inventory stock**?
y=retail_data[:,3].argmax()+1
print(y)

9


In [81]:
#13. How many stores have **inventory less than 1300 units**?
y = retail_data[:,3]
x=y<1300
z=tuple(x)
z.count(True)

3

In [101]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
y=retail_data[:,4]
x=retail_data[:,3]
z=y/x
print(z.argmax()+1)

9


In [102]:
#15. Which stores have **returns greater than 15 units**?
y = retail_data[:,4]
x=y>15
z=tuple(x)
z.count(True)

3

In [106]:
#16. Is there a **positive correlation** between sales and customers?
y = retail_data[:,2]
x = retail_data[:,1]
z=np.corrcoef(x,y)
len(z)

2

In [112]:
#17. Which store has **high customer visits but low sales**?
y = retail_data[:,2]
x = retail_data[:,1]
z=np.corrcoef(x,y)
print(z.argmin()+1)

2


In [113]:
#18. Which store has **low customers but high sales**?
y = retail_data[:,2]
x = retail_data[:,1]
z=np.corrcoef(x,y)
print(z.argmax()+1)

4


In [120]:
#19. How many stores have **sales per customer above ₹90**?
y = retail_data[:,1]
x=retail_data[:,2]
z=y/x
i=z>90
j=tuple(i)
j.count(True)

0

In [ ]:
#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?


In [121]:
#21. If profit margin is **20% of sales**, what is the **profit per store**?
y = 0.20 * retail_data[:,1]
print(y)

[5000. 6400. 5600. 8200. 7000. 5400. 7800. 6000. 9000. 6600.]


In [122]:
#22. Which store has the **highest profit**?
y = 0.20 * retail_data[:,1]
print(y.argmax()+1)

9


In [123]:
#23. Which store has the **lowest profit**?
y = 0.20 * retail_data[:,1]
print(y.argmin()+1)

1


In [127]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
y=retail_data[:,1]
x = 0.10 * retail_data[:,1]
print(y+x)

[27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [130]:
#25. How will **total profit** change with the 10% sales increase?
y=retail_data[:,1]
z=0.1*retail_data[:,1]
x=y+z
p1=0.2 * y
p2=0.2 * x
print(p2-p1)

[500. 640. 560. 820. 700. 540. 780. 600. 900. 660.]


**Operational Strategy**

In [134]:
#26. Which stores need **inventory restocking** based on sales and current stock?
y = retail_data[:,1]
x = retail_data[:,4]
z=np.corrcoef(x,y)
z

array([[1.        , 0.91568893],
       [0.91568893, 1.        ]])

In [144]:
#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
y= retail_data[:,1].mean()
x = retail_data[:,2].mean()
z=retail_data[(retail_data[:,1]>y)&(retail_data[:,2]>x)]
print(z[:,0])

[4 7 9]
